### ISSUE TITLE
Bricked 400D when inserting card containing Test.fir

### ISSUE THREAD

**Issue by ricaroo** [400plus/400plus#435]
Hi, 
I've followed the instructions stated on the page, but when doing the first step, when I inserted the CF card containing the file, my camera froze up with no way of switching it off (off yields green power light still). Retried with another CF card and same issue arises as a result. Any fixes?

**Comment by eduperez** [comment]
Could you please list the exact sequence of steps you performed?

Edu.

**Comment by ricaroo** [comment]
Hi,
I tried out the later steps, which was to reformat the CF card and making it bootable with Cardtricks, then formatting the CF card again using the computer's quick format because i realised that I needed to add the test.fir file to begin with. Once i inserted that CF card into the camera, it remained on and had no other responses. I waited for 10 minutes, turned it off by removing the battery, went to make the CF card bootable via the Cardtricks, inserted it, but camera refuses to show LCD screen. Removed SD card and tried another CF card, but nothing shows on the screen as well.

Regards,
Eric

**Comment by eduperez** [comment]
Looks like your camera is already prepared to use 400plus, and thus you do
not need the TESTFIR.FIR file at all. Then, you prepared a card with
Cardtricks, but only did a quick format later; it is still a prepared card,
but it lacks the AUTOEXEC.BIN file, and that is why your camera refuses to
boot.

You must either complete the preparation and copy the AUTOEXEC.BIN file to
the card, of format it completely.

Edu.

**Comment by ricaroo** [comment]
Hi edu, I've already done the following, to reformat the card completely, but the LCD Screen still remains blank and unable to write into the CF card! Is there anything you could do to help remove 400plus completely from the camera? It seems to have already messed up the reading capabilities of the camera, and the camera is no longer able to read and write onto the CF card! It operates fine without CF card inserted though.

**Comment by eduperez** [comment]
But 400plus does not get installed on the camera: the TESTFIR.FIR procedure
only activates a switch in the camera; that switch tells the camera to look
for an AUTOEXEC.BIN file, if the card has been made bootable. There is a
procedure to disable that switch, but you have to use a CF card.

However, I have just one explanation for the behavior you are experiencing:
the camera already has the flag activated and the card is still bootable;
in that case, the camera looks for the AUTOEXEC.BIN file, and fails to boot
because there is no such file in the card.

You can try to go forward, and just copy the AUTOEXEC.BIN file to the card.
Or you can try to go backwards, and completely format the card; I cannot
try it right now, but perhaps Window's "complete format" does not clear the
boot flag properly. I would try with EOSCard (http://pel.hu/eoscard/) and
use wrong labels so the camera does not recognize the card.

If that fails... I am out of ideas...

Edu.

**Comment by ricaroo** [comment]
Hi Edu,
Hope you can please help me out here, because this camera was something new i got for travelling and I only tried the 400+ upgrade knowing that it was a low risk operation.

So just to update you, I've alr tried putting in the AUTOEXEC.BIN file into the card, and all the camera 
does is to emit the CF loading light with no progress whatsoever, turning off or turning on the camera also does not work. It's very frustrating, and I'm not sure what else to do at this point. EOScard doesn't work for me too.

Regards,
Eric
![15086988_10154200954152972_1608035047_n](https://cloud.githubusercontent.com/assets/23495716/20437535/3c1ed7e0-adac-11e6-8c03-dae319604888.jpg)

**Comment by 0xAF** [comment]
Hi ricaroo.
As Edu explained, you camera is not bricked.
The camera is prepared for the hack, but your card is is not prepared correctly.
The card is made bootable, but the needed files are not in place.
That's why your camera is trying to load the hack, but it's not there and the camera halts.

You have two options now. Either follow the wiki and prepare your card (you have many options to prepare it)
Or low level format the card, which will remove the bootable flag and the Label of the filesystem.
If you do not know how (or do not want) to low level format the card, you can try this:
Download DD for Windows, from this link: http://www.chrysocome.net/downloads/db8587da54aa4111dd925fdb18dec398/dd-0.6beta3.zip
Then unzip it to C:\DD folder.
Then start cmd and type:
`C:`
`cd \DD`
`dd --list`
Checkout the output and find which device corresponds to your card.
It should be something like `\\.\F:`, or `\\.\G:`, or something like that. 
Then type this command:
`dd if=/dev/zero of=\\.\F: bs=1M count=1`
This will write 1MB of zeroes to the beginning of your card, which is actually a low level format.
After that you will need to format the card in normal way, because after the command above, there will be no FileSystem and the card will be unusable, unless you format it normally. I believe you can format it in the camera too...
**Be careful, if you type `\\.\C:` or any other drive, which is not your card, you will format it permanently.**


Anyway, my suggestion is to try to prepare your card correctly and enjoy 400Plus!

**Comment by ricaroo** [comment]
Hi 0xAF,
Make no mistake, i've already did all the suggestions, lowlevel formatting and placing in back into the 400d after formatting, but it's pretty much still stuck in that loading mode. Even after completing and putting the Autoexec.bin file with a root folder of 400PLUS inside the CF card, there is no response from the camera.

The only time the CF card red light went off was when I changed to my alternate NON 400PLUS card, but that card had the same problem of the blank LCD screen, even though there was no alterations to its contents (although it is 16gb vs the first one which is 1gb). Can anyone suggest more alternative solutions to this problem?

Regards,
Eric

**Comment by ricaroo** [comment]
![image](https://cloud.githubusercontent.com/assets/23495716/20440693/037a56f0-adb9-11e6-84ed-1e2481c5131a.png)
![image](https://cloud.githubusercontent.com/assets/23495716/20440728/1d7b6b8e-adb9-11e6-8bbb-8e98ba340912.png)

**Comment by 0xAF** [comment]
Hm, that sound strange... can you try the lowlevel format method, which I described in my previous comment and see if the card starts working again?

**Comment by 0xAF** [comment]
I'm asking that, because I do not know how you made the low level format. And this method will do what is needed for sure.

**Comment by ricaroo** [comment]
Hi 0xAF,
I have already tried that and reformatted, followed by a reformat from the pc and reinsertion, bt the same red light constantly stayed on on my camera again, with no changes.

Regards,
Eric

**Comment by 0xAF** [comment]
So let's sum it.
You have 2 cards. One prepared (and formated after that) and one that was not prepared for the hack?
The camera does not work with both cards, but works without card?

**Comment by ricaroo** [comment]
Yes, that's the summary, and attached is the low level format code that I've followed through and the final result 
![image](https://cloud.githubusercontent.com/assets/23495716/20441190/65726d1e-adbb-11e6-967d-e473cb9082f6.png)
![image](https://cloud.githubusercontent.com/assets/23495716/20441195/6ba59b3e-adbb-11e6-806d-703f12b4d3be.png)

**Comment by 0xAF** [comment]
The commands I've written above are not executed correctly...
You did not succeed doing the low level format.
you have a space character between the `bs` and `=1M` parts of the command.
that's why it failed to do the low level format.

**Comment by 0xAF** [comment]
Sorry, I saw your next command, which is corrected. But still the low level format did not succeed.
Try removing and then reinserting the CF card to the reader.
Then do not open windows explorer or any other file manager. Just execute the last command.
It seems some other process (perhaps the file manager/windows explorer) is using the card, and the `dd` command cannot do it's job.

**Comment by 0xAF** [comment]
I should learn to read all of it .... damn it... sorry, I saw your last command ;) Let me think a bit...

**Comment by 0xAF** [comment]
Hm, this is weird. Can you try the `dd` command, but without the last parameter `count=1`.
It will put zeroes over the whole card. It will take some time. Let me know how much time it takes and do not format the card after that. Put it in the camera and see if it starts. If it works, then format the card in the camera.

**Comment by ricaroo** [comment]
That took a total of 2 minutes, but the same red light flashes out for this card and nothing displays on the LCD screen as per before

**Comment by 0xAF** [comment]
Hm, can you look inside the camera slot for the CF card (with a flashlight) and check if all the pins are ok. This is very strange. Nobody reported such problems before and 400Plus is used by tenth or hundreds of thousand. And I never heard of similar problems in Magic Lantern too. The principle of enabling the hack there (in ML) is the same too...
If you have another battery, please try it. I have slight memories that I had some problems with dead batteries...

**Comment by ricaroo** [comment]
There is a single bent pin within the card reader, not too sure if it's the thing that's causing the problem, Battery is definitely not an issue as I've interchanged with both batteries. Was wondering if the 400plus was the problem because it was unlikely that my pins got damaged the same time as the loading of the hack :S

**Comment by 0xAF** [comment]
Every pull and push of the card from/to the card slot can actually damage it.
Double check the card slot is the pin bent, or you just see some pins which a higher than others. Because the slot should have few pins higher than others (or at least one pin higher)

**Comment by 0xAF** [comment]
If there is a bent pin, you can try to fix it with nippers, but please do not do more damage, which is quite possible with the nippers. If you're unsure, better take it to someone who will open the camera and fix the pins...

**Comment by 0xAF** [comment]
Please post the final result, so we sleep calmly. :)
And please do try 400Plus after that, otherwise you will miss a lot. :)

**Comment by danieltroger** [comment]
Ya, and a completely dumb answer: maybe you've just got your screen turned off somehow? (Well but then your card LED wouldn't be glowing)
Does wildly pressing buttons do anything?

**Comment by ricaroo** [comment]
After what seemed like hours of keyhole surgery, I managed to align the pins in the camera and it worked like a charm! Thanks to all who have helped in one way or another for this, can't thank you guys enough for your patience! Guess i really gotta be more careful with inserting CF cards!
