### ISSUE TITLE
Function lost after install.

### ISSUE THREAD

**Issue by effelle** [400plus/400plus#451]
My 50D is dead, and I decided to give a spin on my old 400D with this hack (Release 20160404-09). 
The camera was checked before applying the hack.
I've Installed the latest testfir.fir, then formatted and made bootable a 2GB (Fat) and 8GB (Fat32) and added the latest autoexec.bin and the 400PLUS folder. The hack is present, however the front wheel stopped working and the camera show now a huge delay when I turn it off and a continuously blinking print led (blue) and cf led (red). As a result I can now use it just on automatic mode or on the other presets, since the wheel on TV, AV, P and M no longer works.

See video here: https://youtu.be/FhoKabOxprA

I tried a complete reset of the camera, including removing the backup battery with no luck. Reverting the hack (another 2GB CF formatted onboard) did not solved the issue, then probably something wrong happen when I installed the firmware and now I can't revert to the stock one. 
Any clue/help?

Thanks,

Federico

**Comment by eduperez** [comment]
The wheel could be broken, but that long delay when switching off can only be attributed to a software error. Also, if it fails with a fresh card (formatted and without any file), then it looks like there was something wrong with the installation of TESTFIR.FIR.

This step just changes one flag in the camera, nothing else is installed, and there is no going back to the original firmware because the original firmware is still there. We could try to revert the flag, but it is a dangerous procedure, and can do more harm than good; I would investigate a bit first.

What firmware is installed in your camera?

**Comment by effelle** [comment]
Sure @eduperez , the wheel could be broken, but you must admit it would be a perfect timing, because stopped working after the installation of testfir.fir.  
My camera where already on the latest available firmware form Canon (1.1.1).

**Comment by danieltroger** [comment]
I've moved to a newer camera with magiclantern, but is there anything preventing you from reflashing 1.1.1 and then testfir.fir? That's what I'd do, but I don't know if reflashing breaks something on the 400D

**Comment by effelle** [comment]
@danieltroger, good idea.
I'll just wait @eduperez to know if I can reflash the stock one or not just to be sure.

**Comment by eduperez** [comment]
Yes, I also think that the wheel is not broken. And I also think that trying to flash 1.1.1 is be a good idea (if the camera allows it, I fear it will refuse to install the same firmware).

**Comment by 0xAF** [comment]
I think reflashing will not fix the problem. The testfir.fir file did not flash anything, it only changes one bootflag. So on the next boot the camera will look at the CF card for the file AUTOEXEC.BIN. This has nothing to do with your firmware. Even if you reflash it, I believe that it will not revert this flag. But yet again, the flag itself does not change anything for you.
I think it is some hardware failure. After the so many users used/using 400+, I do not think it has to do anything with the hack itself. It could be some temporary breakage in the battery or whatever which resulted in this problem, but I can only speculate here. Try to reflash it if the camera allows you to, but I will be greatly surprised if this helps.

Anyway, this looks more like there is some electronic board under the two dials (rotary encoders), which probably has one cable connection to the main board and the processor. This cable could be broken and lost one of it's pins (most probably some common pin, like the ground or something). Hence the both dials are not working. But this would mean to open the camera and check the connections, for which is probably better to go to a service or technician to do this for you. This is just another speculation again.

As for the turning off the camera, it seems it turns off and tries to turn on again. You can see the blue light blinking for short time, because it tries to start the hack again. Why the camera does that, I cannot think of right now, but I have some blurry memory that there was similar case before, which I cannot remember why was doing it.

What happens if you pullout the CF and start the camera? Does it work properly? Or does it turn off properly?


EDIT: Just remembered that when you put the battery and close the door it tries to boot the firmware and the hack for very short time, then turns off. I have a very wild guess, but could you please try to open the battery door, turn off the camera by the switch and close the battery door while the camera is off by the switch. See if it still flashes the leds in loop or just once. Before turning it on by the switch.

**Comment by 0xAF** [comment]
As `owerlord` explained here: https://chdk.setepontos.com/index.php/topic,1618.0.html
His bootflags were broken after testing some code and the way he fixed it is with reflashing the bootloader.
I'm pointing to this only to show that reflashing the firmware itself will probably not reflasah the bootloader, hence the bootflags will be left alone.
***DO NOT FLASH OR START ANYTHING FROM THE LINKED THREAD***
And one more time, the bootflag is not your problem, so there is no point in trying to revert it. I'm pretty sure about this.

**Comment by effelle** [comment]
@0xAF thanks for your exhaustive reply. 

The camera worked fine literally seconds before flashing the hack, but if the hack just add a flag to enable the autexec on my CF and as we are talking about a camera left in a drawer for a long time, could be just a unfortunate coincidence of an hardware failure. 
I loved my 400D before buying a 50D, then simply I'm trying to revive it until I'll decide what camera buy.

- I've re-flashed the original firmare and tested the camera. No wheel and shows delay when off (just the red led is blinking).

- I've re-flashed the hack: no wheel and the camera shows delay when off (both leds are blinking).

- Without CF, faster off and red led blinking.

The more I look, the more I think is an hardware failure, but I don't think is economically advantageous send the camera to the nearest service point. Probably will costs more than the camera itself.
Ok, I'm out of luck. I'll survive without my reflex for some weeks!

**Comment by 0xAF** [comment]
I've edited my comment above, but it's pointless to do the test, after what you wrote in your last comment.
As for the service, I agree.
I do not know where you live, but here at my place we have more like general purpose small services, or we just know one or two guys who are good at electronics and it will not cost much to open it and do some testing. If you have something similar, you could try there, because the official service will be expensive, as you wrote. And if you give up on the camera, do not throw it away. You can send it to me (if the postage is in normal range) and I can give it to some technician around. Would not cost much (besides postage), probably not more than 20-30 euro. Or if you totally lost interest in the camera, you can probably gift it to someone who's willing to fix it.

**Comment by effelle** [comment]
I'm Italian, but due to my work now I'm operating business in Brazil. 
As far as I can see I have two option here, disassemble the camera and have a look inside, more for fun,   since I have all the equipment I need (I worked 8 years as a technician for Dell, specialized on notebook and PocketPC) or wait the next trip to Italy and send to a Canon Center. Send it overseas from here will costs more than the camera, trust me. 
lost interest in my camera? Not really, was my first one on digital era. I know it will sound strange but is all about the first love. :)

**Comment by 0xAF** [comment]
Hehe, I'm glad you feel like that about the camera.
Ok, if you go for opening, and since you are technician, you know to handle with care.
At least you can see if there is a visible damage on the cables or the boards.
Good luck.

**Comment by effelle** [comment]
Thanks!
I will close the issue now, but I'll send you some news for the sake of knowledge: someone could come across the same situation.
